Fix: login-logo URL can be incorrect for all the sub-sites in a network
humanmade/altis-cms pull request #283
Opened 2020-11-05 12:45 UTC by Nikschavan

Fix #259

2020-11-05 12:45 UTC, Nikschavan commented
Wondering if this will be backported to v4 as well?

2020-11-05 15:12 UTC, roborourke requested changes
Minor update, thanks for doing this!

2020-11-05 15:12 UTC, roborourke commented on inc/namespace.php
> +			background-image: url('<?php echo esc_url( get_site_url( 1, $logo ) ); ?>');
Can this use `get_main_site_id( get_main_network_id() )` instead? I think 1 is generally correct but in some really bizarre circumstances it's not always the case

2020-11-05 15:12 UTC, roborourke commented on inc/namespace.php
> +			background-image: url('<?php echo esc_url( get_site_url( 1, $logo ) ); ?>');
```suggestion
			background-image: url('<?php echo esc_url( get_site_url( get_main_site_id( get_main_network_id() ), $logo ) ); ?>');
```

2020-11-06 11:26 UTC, roborourke approved these changes

2020-11-06 11:27 UTC, merged